### ISSUE TITLE
Add non-flexbox css coverage

### ISSUE THREAD

**Issue by darrenshrwd** [LukaszWatroba/v-modal#9]
The dialog uses flexbox css which does not work with IE9 and many older mobile browsers.

**Comment by LukaszWatroba** [comment]
Right now, you can set `$v-modal-use-flexbox` SCSS variable to `false`, or override default v-dialog element styling to:

``` css
v-dialog {
  margin: 0 auto;
}
v-dialog[middle] {
  top: 50%;
  transform: translateY(-50%);
}
```
